# Autoharness Template Processor for csv-managed
# Generated by Auto-MergeInstall agent
# This script reads .tmpl files, substitutes variables, and writes output artifacts

$ErrorActionPreference = "Stop"

$autoharness_home = "D:\Python314\Lib\site-packages\autoharness\data"
$templates = "$autoharness_home\templates"
$workspace = "D:\Source\GitHub\csv-managed"

# Variable substitution map
$vars = @{
    '{{PROJECT_NAME}}' = 'csv-managed'
    '{{PRIMARY_LANGUAGE}}' = 'Rust'
    '{{PRIMARY_LANGUAGE_LOWER}}' = 'rust'
    '{{LANGUAGE_VERSION}}' = '2024'
    '{{LANGUAGE_NOTES}}' = '(Rust 2024 edition)'
    '{{BUILD_COMMAND}}' = 'cargo build'
    '{{TEST_COMMAND}}' = 'cargo test'
    '{{LINT_COMMAND}}' = 'cargo clippy -- -D warnings'
    '{{FORMAT_COMMAND}}' = 'cargo fmt --all -- --check'
    '{{FORMAT_FIX_COMMAND}}' = 'cargo fmt --all'
    '{{BUILD_CHECK_COMMAND}}' = 'cargo check --all-targets'
    '{{FORMAT_CHECK_COMMAND}}' = 'cargo fmt --all -- --check'
    '{{TEST_DIR}}' = 'tests/'
    '{{SOURCE_DIR}}' = 'src/'
    '{{CI_PLATFORM}}' = 'GitHub Actions'
    '{{CI_WORKFLOW_GLOB}}' = '**/.github/workflows/*.yml'
    '{{REPO_OWNER}}' = 'softwaresalt'
    '{{REPO_NAME}}' = 'csv-managed'
    '{{BUILD_TOOL}}' = 'cargo'
    '{{FORMATTER}}' = 'rustfmt'
    '{{LINTER}}' = 'clippy'
    '{{TEST_RUNNER}}' = 'cargo test'
    '{{UNSAFE_POLICY}}' = '#![forbid(unsafe_code)] unless justified with // SAFETY: comment'
    '{{ERROR_PATTERN}}' = 'Result<T, Error>'
    '{{DOC_COMMENT_STYLE}}' = '/// doc comment'
    '{{LANGUAGE_FILE_GLOB}}' = '**/*.rs'
    '{{UNIMPLEMENTED_MARKER}}' = 'unimplemented!("Worker: ...")'
    '{{MCP_SDK}}' = ''
    '{{MCP_TRANSPORT}}' = ''
    '{{MCP_PROJECT_STRUCTURE}}' = ''
    '{{DATE}}' = '2026-05-21'
    '{{PROJECT_DESCRIPTION}}' = 'High-performance Rust CLI (edition 2024) that streams, transforms, validates, indexes, and profiles large CSV/TSV datasets'
    '{{CI_NOTES}}' = 'GitHub Actions with cargo caching, single lint-test job'
    '{{ADDITIONAL_STACK_ROWS}}' = ''
    '{{ADDITIONAL_COMMANDS}}' = ''
    '{{NAMING_CONVENTIONS}}' = 'snake_case for variables and functions, PascalCase for types and traits, SCREAMING_SNAKE_CASE for constants'
    '{{DOCUMENTATION_CONVENTIONS}}' = '/// doc comments on all public items, //! module-level Rustdoc'
    '{{ERROR_HANDLING_CONVENTIONS}}' = 'anyhow::Result for fallible operations, .context() for error context'
    '{{LINT_POLICY}}' = 'All clippy warnings are hard errors (-D warnings)'
    '{{ERROR_HANDLING_POLICY}}' = 'All errors must be propagated via Result with contextual messages'
    '{{TEST_STRUCTURE}}' = 'Unit tests in src/ (inline #[cfg(test)]), integration tests in tests/'
    '{{COMMIT_SCOPES}}' = "* ``append`` — Multi-file CSV concatenation`n* ``cli`` — CLI argument definitions`n* ``columns`` — Column listing`n* ``data`` — Value enum and typed parsers`n* ``derive`` — Derived column expressions`n* ``expr`` — Expression evaluation`n* ``filter`` — Row-level filter parsing`n* ``frequency`` — Frequency counts`n* ``index`` — B-tree index operations`n* ``install`` — Self-install`n* ``io`` — Reader/writer I/O utilities`n* ``join`` — CSV join operations`n* ``process`` — Process subcommand`n* ``rows`` — Row-level parsing`n* ``schema`` — Schema model and inference`n* ``stats`` — Summary statistics`n* ``table`` — ASCII table rendering`n* ``verify`` — Schema verification`n* ``docs`` — Documentation`n* ``tests`` — Test fixtures and integration tests`n* ``bench`` — Benchmarks`n* ``ci`` — CI/CD configuration`n* ``harness`` — Agent harness artifacts"
    '{{EXAMPLE_SCOPE}}' = 'cli'
    '{{QUALITY_GATE_1_NAME}}' = 'fmt'
    '{{QUALITY_GATE_1}}' = 'cargo fmt -- --check'
    '{{QUALITY_GATE_2_NAME}}' = 'clippy'
    '{{QUALITY_GATE_2}}' = 'cargo clippy --all-targets --all-features -- -D warnings'
    '{{QUALITY_GATE_3_NAME}}' = 'test'
    '{{QUALITY_GATE_3}}' = 'cargo test --all-targets --all-features'
    '{{QUALITY_GATE_4_NAME}}' = 'build'
    '{{QUALITY_GATE_4}}' = 'cargo build --release'
    '{{POLL_INTERVAL}}' = '30'
    '{{MAX_WAIT}}' = '600'
    '{{BACKLOG_TOOL_NAME}}' = 'backlogit'
    '{{BACKLOG_DIRECTORY}}' = '.backlogit'
    '{{BACKLOG_TOOL_TYPE}}' = 'both'
    '{{OP_CREATE_MCP}}' = 'backlogit_create_item'
    '{{OP_LIST_MCP}}' = 'backlogit_list_items'
    '{{OP_GET_MCP}}' = 'backlogit_get_item'
    '{{OP_UPDATE_MCP}}' = 'backlogit_update_item'
    '{{OP_MOVE_MCP}}' = 'backlogit_move_item'
    '{{OP_SEARCH_MCP}}' = 'backlogit_search_items'
    '{{OP_COMPLETE_MCP}}' = 'backlogit_move_item'
    '{{OP_CREATE_CLI}}' = 'backlogit add'
    '{{OP_LIST_CLI}}' = 'backlogit list'
    '{{OP_GET_CLI}}' = 'backlogit show {id}'
    '{{OP_UPDATE_CLI}}' = 'backlogit update {id}'
    '{{OP_MOVE_CLI}}' = 'backlogit move {id} {status}'
    '{{OP_SEARCH_CLI}}' = 'backlogit search {query}'
    '{{OP_COMPLETE_CLI}}' = 'backlogit done {id}'
    '{{STATUS_QUEUED}}' = 'queued'
    '{{STATUS_ACTIVE}}' = 'active'
    '{{STATUS_DONE}}' = 'done'
    '{{STATUS_BLOCKED}}' = 'blocked'
    '{{FIELD_TASK_ID}}' = 'id'
    '{{FIELD_TITLE}}' = 'title'
    '{{FIELD_STATUS}}' = 'status'
    '{{FIELD_LABELS}}' = 'labels'
    '{{FIELD_PARENT_ID}}' = 'parent'
    '{{FIELD_TYPE}}' = 'type'
    '{{FIELD_DESCRIPTION}}' = 'description'
    '{{BACKLOG_TOOLS}}' = 'backlog'
    '{{EXTENDED_OPERATIONS_TABLE}}' = ''
    '{{FEATURE_SHIPMENTS}}' = 'true'
    '{{OP_CREATE_SHIPMENT_MCP}}' = 'backlogit_create_shipment'
    '{{OP_SYNC_INDEX_MCP}}' = 'backlogit_sync_index'
    '{{OP_SYNC_INDEX_CLI}}' = 'backlogit sync'
    '{{OP_GET_SHIPMENT_MCP}}' = 'backlogit_get_shipment'
    '{{OP_LIST_SHIPMENTS_MCP}}' = 'backlogit_list_shipments'
    '{{OP_CLAIM_SHIPMENT_MCP}}' = 'backlogit_claim_shipment'
    '{{OP_SHIP_SHIPMENT_MCP}}' = 'backlogit_ship_shipment'
    '{{OP_ADD_TO_SHIPMENT_MCP}}' = 'backlogit_add_to_shipment'
    '{{OP_RETURN_BLOCKED_MCP}}' = 'backlogit_return_blocked'
    '{{OP_CREATE_CHECKPOINT_MCP}}' = 'backlogit_create_checkpoint'
    '{{OP_LIST_CHECKPOINTS_MCP}}' = 'backlogit_list_checkpoints'
    '{{OP_GET_CHECKPOINT_MCP}}' = 'backlogit_get_checkpoint'
    '{{OP_RESOLVE_CHECKPOINT_MCP}}' = 'backlogit_resolve_checkpoint'
    '{{OP_POLL_HOOK_EVENTS_MCP}}' = 'backlogit_poll_hook_events'
    '{{OP_ACK_HOOK_EVENTS_MCP}}' = 'backlogit_ack_hook_events'
    '{{SUFFIX_FEATURE}}' = 'F'
    '{{SUFFIX_CHORE}}' = 'C'
    '{{SUFFIX_TASK}}' = 'T'
    '{{SUFFIX_SPIKE}}' = 'SP'
    '{{SUFFIX_DELIBERATION}}' = 'D'
    '{{SUFFIX_BUG}}' = 'B'
    '{{SUFFIX_EPIC}}' = 'E'
    '{{SUFFIX_SUBTASK}}' = 'ST'
    '{{SUFFIX_SHIPMENT}}' = 'S'
    '{{DOCS_ROOT}}' = 'docs'
    '{{DOCS_COMPOUND}}' = 'docs/compound'
    '{{DOCS_PLANS}}' = 'docs/plans'
    '{{DOCS_DECISIONS}}' = 'docs/decisions'
    '{{DOCS_MEMORY}}' = 'docs/memory'
    '{{DOCS_CLOSURE}}' = 'docs/closure'
    '{{DOCS_DESIGN_DOCS}}' = 'docs/design-docs'
    '{{DOCS_PRODUCT_SPECS}}' = 'docs/product-specs'
    '{{LANGUAGE_VERSION_DETAIL}}' = 'Rust 2024 edition'
    '{{FILE_EXT}}' = 'rs'
    '{{HARNESS_MANIFEST_PATH}}' = '.autoharness/harness-manifest.yaml'
    '{{AUTOHARNESS_VERSION}}' = '1.4.5'
    '{{COPILOT_EXE_PATH}}' = 'copilot'
    '{{BROWSER_CLI}}' = 'agent-browser'
    '{{BROWSER_HEADLESS_FLAG}}' = '--headless'
    '{{EXPERIMENT_BRANCH_PREFIX}}' = 'experiment/'
    '{{EXPERIMENT_RESULTS_DIR}}' = 'docs/experiments'
    '{{AGENTIC_CONFIG_GLOB}}' = '.github/**,.vscode/**'
    '{{SOURCE_GLOB}}' = 'src/**'
    '{{DOCS_SECURITY}}' = 'docs/security'
    '{{REPOSITORY_OPERATING_MODEL}}' = 'Single-repository Rust CLI project. The Stage agent manages planning and triage; the Ship agent manages implementation, review, and delivery. Both agents share the same workspace and follow the constitution and workflow policies.'
    '{{PROJECT_STRUCTURE}}' = "src/           — Application source (lib.rs, cli.rs, 16 modules)`nsrc/main.rs    — Binary entry point`ntests/         — Integration tests (assert_cmd + predicates)`ntests/data/    — Fixture CSV and schema YAML files`nbenches/       — Criterion benchmarks`ndocs/          — ADRs, CLI help, operation guides`nspecs/         — Feature specifications and task plans"
    '{{TEST_TIER_DESCRIPTION}}' = 'Unit: cargo test (inline #[cfg(test)] modules), Integration: cargo test --test (tests/ directory), Property: proptest, Benchmark: criterion'
    '{{NAMING_RULES}}' = "* snake_case for functions, methods, variables, modules`n* PascalCase for types, traits, enum variants`n* SCREAMING_SNAKE_CASE for constants and statics`n* Descriptive names; avoid single-letter variables except in closures and iterators"
    '{{CODE_ORGANIZATION_RULES}}' = "* One primary type or trait per module`n* Module declarations in lib.rs`n* Each subcommand in its own module with pub fn execute()`n* Keep function bodies under 100 lines"
    '{{ERROR_HANDLING_RULES}}' = "* Use anyhow::Result for binary crate, thiserror for library error types`n* Propagate with ? operator, add context with .context() or .with_context()`n* Never .unwrap() in production code without proof comment`n* Never println! from deep logic; use log crate macros"
    '{{SAFETY_RULES}}' = "* #![forbid(unsafe_code)] unless justified with // SAFETY: comment`n* All clippy warnings are hard errors`n* Stream data row-by-row; never load entire files into memory`n* Prefer &str and Cow<'_, str> over String cloning"
    '{{PERFORMANCE_RULES}}' = "* Stream CSV data row-by-row using csv::Reader`n* Reuse scratch buffers in hot loops`n* Index-accelerated reads use seek-based I/O`n* collect::<Vec<_>>() on large datasets requires justifying comment`n* Benchmarks in benches/ using criterion"
    '{{TESTING_RULES}}' = "* Unit tests in inline #[cfg(test)] modules`n* Integration tests in tests/ using assert_cmd + predicates`n* Property tests with proptest`n* Use tempfile::tempdir() for ephemeral outputs`n* Test both success and failure paths`n* Add // Invariant: comments above test data"
    '{{DOCUMENTATION_RULES}}' = "* /// doc comments on all public functions, types, traits`n* //! module-level Rustdoc on every source file`n* Examples in doc comments for complex APIs`n* Follow Rust API Guidelines"
    '{{DEPENDENCY_RULES}}' = "* Prefer well-maintained crates from crates.io`n* Pin major versions in Cargo.toml`n* Minimize feature flags to what is needed`n* Use dev-dependencies for test-only crates"
    '{{ANTI_PATTERNS}}' = "* .unwrap() in library code without proof`n* .clone() without justification`n* String in public API return types (prefer &str)`n* Box<dyn Error> (use typed error enums)`n* println! for logging (use log crate)`n* Global mutable state`n* Wildcard imports (use x::*)"
    '{{LANGUAGE_SAFETY_CHECKS}}' = "* unsafe blocks without SAFETY comments`n* .unwrap()/.expect() without proof of infallibility`n* Raw pointer dereferences`n* Unchecked array indexing (prefer .get())`n* Missing bounds checks on user-supplied indices"
    '{{LANGUAGE_IDIOM_CHECKS}}' = "* Manual loops that should be iterator chains`n* Unnecessary .clone() calls`n* String allocation where &str suffices`n* match arms that could use if let`n* Verbose error handling that could use ?"
    '{{LANGUAGE_ERROR_HANDLING_CHECKS}}' = "* .unwrap() without justification`n* Swallowed errors (let _ = fallible_call())`n* Missing .context() on ? propagation`n* panic! in library code`n* Error types that lose source chain"
    '{{LANGUAGE_PERFORMANCE_CHECKS}}' = "* Unnecessary allocations in hot paths`n* collect() without size hint`n* Redundant cloning`n* Unbounded buffering of streaming data`n* Missing #[inline] on trivial getters in hot paths"
    '{{CONCURRENCY_PATTERNS}}' = 'async/await, tokio, rayon, Arc<Mutex<T>>, channels (mpsc, oneshot), thread::spawn, crossbeam'
    '{{SECURITY_CONFIG_RULES}}' = "* Check .github/ for overly permissive allow-lists`n* Check .vscode/settings.json for terminal auto-approve patterns`n* Check for hardcoded credentials or API keys`n* Check for unpinned secrets in CI workflows`n* Check for debug endpoints or verbose logging of sensitive data"
    '{{SECURITY_OWASP_PATTERNS}}' = "* unsafe blocks with unchecked deserialization`n* Command injection via std::process::Command with user input`n* Path traversal via unchecked user-supplied paths`n* Unchecked integer overflow in index arithmetic`n* Missing input validation at system boundaries"
    '{{SECURITY_SCAN_PATTERNS}}' = "* std::process::Command with shell=true or unsanitized arguments`n* File I/O with user-controlled paths without canonicalization`n* Deserialization of untrusted input (serde without validation)`n* Environment variable injection`n* Regex denial-of-service (ReDoS) patterns"
    '{{SECURITY_REVIEW_PATTERNS}}' = "* src/io_utils.rs — file I/O and path handling`n* src/cli.rs — user input parsing`n* src/expr.rs — expression evaluation`n* src/filter.rs — filter parsing`n* Pattern keywords: path, file, open, read, write, execute, command, eval, parse, input, user"
}

function Process-Template {
    param(
        [string]$TemplatePath,
        [string]$OutputPath
    )
    
    $content = Get-Content -Path $TemplatePath -Raw -Encoding UTF8
    foreach ($key in $vars.Keys) {
        $content = $content.Replace($key, $vars[$key])
    }
    
    $dir = Split-Path -Parent $OutputPath
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    
    # Write with UTF-8 no BOM
    [System.IO.File]::WriteAllText($OutputPath, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Output "OK: $OutputPath"
}

# ============ FOUNDATION ============
Process-Template "$templates\foundation\AGENTS.md.tmpl" "$workspace\AGENTS.md"
Process-Template "$templates\foundation\constitution.instructions.md.tmpl" "$workspace\.github\instructions\constitution.instructions.md"
Process-Template "$templates\foundation\copilot-instructions.md.tmpl" "$workspace\.github\copilot-instructions.md"

# ============ INSTRUCTIONS ============
# Technology-specific (Rust variant)
Process-Template "$templates\instructions\technology-rust.instructions.md.tmpl" "$workspace\.github\instructions\rust.instructions.md"

# Universal instructions
$universalInstructions = @(
    'commit-message',
    'markdown',
    'writing-style',
    'git-merge',
    'pull-request',
    'prompt-builder',
    'circuit-breaker',
    'concurrency',
    'architecture-doc',
    'context-efficiency',
    'ci-security',
    'workflows',
    'github-pr-automation',
    'role-enforcement'
)
foreach ($name in $universalInstructions) {
    Process-Template "$templates\instructions\$name.instructions.md.tmpl" "$workspace\.github\instructions\$name.instructions.md"
}

# Backlog integration
Process-Template "$templates\instructions\backlog-integration.instructions.md.tmpl" "$workspace\.github\instructions\backlog-integration.instructions.md"

# Capability pack instructions
$capabilityInstructions = @(
    'backlogit',
    'backlogit-sql-schema',
    'backlogit-yaml-header-tooling',
    'agent-engram',
    'continuous-learning',
    'strict-safety',
    'release-observability',
    'adversarial-review'
)
foreach ($name in $capabilityInstructions) {
    Process-Template "$templates\instructions\$name.instructions.md.tmpl" "$workspace\.github\instructions\$name.instructions.md"
}

# ============ AGENTS ============
# Pipeline agents
Process-Template "$templates\agents\stage.agent.md.tmpl" "$workspace\.github\agents\stage.agent.md"
Process-Template "$templates\agents\ship.agent.md.tmpl" "$workspace\.github\agents\ship.agent.md"
Process-Template "$templates\agents\orchestrator.agent.md.tmpl" "$workspace\.github\agents\orchestrator.agent.md"

# Support agents
Process-Template "$templates\agents\prompt-builder.agent.md.tmpl" "$workspace\.github\agents\prompt-builder.agent.md"

# Expert agent (Rust)
Process-Template "$templates\agents\language-engineer.agent.md.tmpl" "$workspace\.github\agents\rust-engineer.agent.md"

# Security agent
Process-Template "$templates\agents\security-sentinel.agent.md.tmpl" "$workspace\.github\agents\security-sentinel.agent.md"

# Adversarial review agent
Process-Template "$templates\agents\adversarial-review.agent.md.tmpl" "$workspace\.github\agents\adversarial-review.agent.md"

# Research agents
New-Item -ItemType Directory -Path "$workspace\.github\agents\research" -Force | Out-Null
Process-Template "$templates\agents\research\learnings-researcher.agent.md.tmpl" "$workspace\.github\agents\research\learnings-researcher.agent.md"

# Review personas
New-Item -ItemType Directory -Path "$workspace\.github\agents\review" -Force | Out-Null
$reviewPersonas = @(
    'architecture-strategist',
    'constitution-reviewer',
    'scope-boundary-auditor',
    'concurrency-reviewer',
    'security-reviewer',
    'security-lens-reviewer'
)
foreach ($name in $reviewPersonas) {
    Process-Template "$templates\agents\review\$name.agent.md.tmpl" "$workspace\.github\agents\review\$name.agent.md"
}
# Technology reviewer → rust-reviewer
Process-Template "$templates\agents\review\technology-reviewer.agent.md.tmpl" "$workspace\.github\agents\review\rust-reviewer.agent.md"

# ============ SKILLS ============
$skills = @(
    'build-feature',
    'fix-ci',
    'impl-plan',
    'deliberate',
    'spike',
    'plan-harden',
    'compact-context',
    'compound',
    'compound-refresh',
    'harness-architect',
    'harvest',
    'pr-lifecycle',
    'safety-modes',
    'file-lock',
    'skill-search',
    'security-audit',
    'runtime-verification',
    'operational-closure',
    'observe',
    'learn',
    'evolve',
    'iterative-experiment',
    'harness-doctor',
    'plan-review',
    'review',
    'shipment-reconcile',
    'browser-automation'
)
foreach ($name in $skills) {
    $tmplPath = "$templates\skills\$name\SKILL.md.tmpl"
    if (Test-Path $tmplPath) {
        Process-Template $tmplPath "$workspace\.github\skills\$name\SKILL.md"
    } else {
        Write-Output "SKIP: $tmplPath (not found)"
    }
}

# ============ POLICIES ============
New-Item -ItemType Directory -Path "$workspace\.github\policies" -Force | Out-Null
Process-Template "$templates\policies\workflow-policies.md.tmpl" "$workspace\.github\policies\workflow-policies.md"

# ============ PROMPTS ============
Process-Template "$templates\prompts\ping-loop.prompt.md.tmpl" "$workspace\.github\prompts\ping-loop.prompt.md"

# ============ SCRIPTS ============
# File-lock scripts
$fileLockScripts = @('acquire_lock.ps1', 'acquire_lock.sh', 'release_lock.ps1', 'release_lock.sh')
New-Item -ItemType Directory -Path "$workspace\scripts" -Force | Out-Null
foreach ($script in $fileLockScripts) {
    $src = "$templates\skills\file-lock\scripts\$script"
    if (Test-Path $src) {
        Copy-Item -Path $src -Destination "$workspace\scripts\$script" -Force
        Write-Output "OK: scripts/$script"
    }
}

# Skill-search scripts
$skillSearchScripts = @('search.ps1', 'search.sh')
foreach ($script in $skillSearchScripts) {
    $src = "$templates\skills\skill-search\scripts\$script"
    if (Test-Path $src) {
        Copy-Item -Path $src -Destination "$workspace\scripts\$script" -Force
        Write-Output "OK: scripts/$script"
    }
}

# Startup scripts
Process-Template "$templates\scripts\start.ps1.tmpl" "$workspace\start.ps1"
Process-Template "$templates\scripts\start.sh.tmpl" "$workspace\start.sh"

# ============ BACKLOG STRUCTURE ============
New-Item -ItemType Directory -Path "$workspace\.backlogit\queue" -Force | Out-Null
New-Item -ItemType Directory -Path "$workspace\.backlogit\archive" -Force | Out-Null

# Backlog config
@"
# Backlogit configuration for csv-managed
# Generated by autoharness

prefix_map:
  feature: F
  chore: C
  task: T
  spike: SP
  deliberation: D
  bug: B
  epic: E
  subtask: ST
  shipment: S

statuses:
  - queued
  - active
  - done
  - blocked

labels: []
"@ | Set-Content -Path "$workspace\.backlogit\config.yml" -Encoding UTF8 -NoNewline

# Stash file
@"
# Stash

Parked ideas and deferred outcomes not yet promoted to backlog items.

---
"@ | Set-Content -Path "$workspace\.backlogit\queue\.stash.md" -Encoding UTF8 -NoNewline

# ============ BACKLOG REGISTRY ============
Copy-Item -Path "$templates\backlog\registries\backlogit.registry.yaml" -Destination "$workspace\.autoharness\backlog-registry.yaml" -Force
Write-Output "OK: .autoharness/backlog-registry.yaml"

# ============ KNOWLEDGE DIRECTORIES ============
$docsDirs = @(
    "$workspace\docs\compound",
    "$workspace\docs\plans",
    "$workspace\docs\decisions",
    "$workspace\docs\memory",
    "$workspace\docs\closure",
    "$workspace\docs\design-docs",
    "$workspace\docs\product-specs"
)
foreach ($dir in $docsDirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Output "OK: Created $dir"
    }
}

# ============ COMMUNITY TEMPLATES ============
# ADR Generator
Process-Template "$templates\community\agents\adr-generator.agent.md.tmpl" "$workspace\.github\agents\adr-generator.agent.md"

# Code Review Generic
Process-Template "$templates\community\instructions\code-review-generic.instructions.md.tmpl" "$workspace\.github\instructions\code-review-generic.instructions.md"

# Agent Safety
Process-Template "$templates\community\instructions\agent-safety.instructions.md.tmpl" "$workspace\.github\instructions\agent-safety.instructions.md"

# Skills from community
$communitySkills = @(
    'acquire-codebase-knowledge',
    'writing-plans',
    'brainstorming',
    'changelog-generator',
    'receiving-code-review',
    'debugging',
    'verification-before-completion',
    'simplifying-code',
    'document-review',
    'meta-prompting',
    'writing-tests',
    'skill-creator',
    'mcp-builder'
)
foreach ($name in $communitySkills) {
    $tmplPath = "$templates\community\skills\$name\SKILL.md.tmpl"
    if (Test-Path $tmplPath) {
        Process-Template $tmplPath "$workspace\.github\skills\$name\SKILL.md"
    } else {
        Write-Output "SKIP: Community skill $name (not found)"
    }
}

Write-Output ""
Write-Output "=== Template processing complete ==="
